IMAGE_SIZE = 256

DATASET_ROOT = "danbooru2020_filter_face_nobg_anno_clean"
SAVE_PATH = "checkpoints_clip"

CODEBOOK_DIM = 512
VOCAB_SIZE = 5600

DVAE_NUM_LAYERS = 3
DVAE_NUM_TOKENS = 16384
DVAE_HIDDEN_DIM = 256
DVAE_NUM_RESNET_BLOCKS = 2

DALLE_TEXT_SEQ_LEN = 127
DALLE_DEPTH = 32
DALLE_HEADS = 8
DALLE_DIM_HEAD = 64
DALLE_ATTN_DROPOUT = 0.05
DALLE_FF_DROPOUT = 0.05

CLIP_VISUAL_ENC_DEPTH = 6
CLIP_PATCH_SIZE = 32
CLIP_HEADS = 8
CLIP_DIM_LATENT = 512