IMAGE_SIZE = 128

DATASET_ROOT = "FACE_PIXIV/CLEAN_PIXIV"
SAVE_PATH = "ckpts"

CODEBOOK_DIM = 512
VOCAB_SIZE = 4096

DVAE_NUM_LAYERS = 3
DVAE_NUM_TOKENS = 8192
DVAE_HIDDEN_DIM = 256
DVAE_NUM_RESNET_BLOCKS = 2

DALLE_TEXT_SEQ_LEN = 80
DALLE_DEPTH = 32
DALLE_HEADS = 8
DALLE_DIM_HEAD = 64
DALLE_ATTN_DROPOUT = 0.05
DALLE_FF_DROPOUT = 0.05
